<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Templates_model extends CI_Model
{

    public $table = 'templates';
    public $id = 'templateId';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*')->from($this->table)->join('products', 'templates.productId = products.productId')->order_by($this->id, $this->order);
        // $this->db->order_by($this->id, $this->order);
        return $this->db->get()->result();
    }

    function get_all_products()
    {
        $this->db->order_by('productId', $this->order);
        return $this->db->get('products')->result();
    }

    function get_product_by_id($id)
    {
        $this->db->where('productId', $id);
        return $this->db->get('products')->row();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('templateId', $q);
	$this->db->or_like('templateTitle', $q);
	$this->db->or_like('templateDescription', $q);
	$this->db->or_like('templateThumbnail', $q);
	$this->db->or_like('templateImageUrl', $q);
	$this->db->or_like('templateJson', $q);
	$this->db->or_like('templatePrice', $q);
	$this->db->or_like('templateType', $q);
	$this->db->or_like('templateDate', $q);
	$this->db->or_like('productId', $q);
	$this->db->or_like('adminId', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('templateId', $q);
	$this->db->or_like('templateTitle', $q);
	$this->db->or_like('templateDescription', $q);
	$this->db->or_like('templateThumbnail', $q);
	$this->db->or_like('templateImageUrl', $q);
	$this->db->or_like('templateJson', $q);
	$this->db->or_like('templatePrice', $q);
	$this->db->or_like('templateType', $q);
	$this->db->or_like('templateDate', $q);
	$this->db->or_like('productId', $q);
	$this->db->or_like('adminId', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Templates_model.php */
/* Location: ./application/models/Templates_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-17 12:26:02 */
/* http://harviacode.com */